# Evaluación I
## Evaluación de contenidos 1 Módulo 2
Bienvenidas a una nueva evaluación del Bootcamp de Análisis de Datos de Adalab.
Como en evaluaciones anteriores dispondréis de 2 tardes (aproximadamente 8 horas para la resolución de todos los ejercicios propuestos).
Estos ejercicios se tendrán que defender en el día de la evaluación de forma individual con vuestra tutora en una simulación de entrevista técnica donde tendréis de 20 minutos para resolver o explicar los ejercicios propuestos entregados.

## Ejercicios de NumPy

    1. Importa la librería de NumPy.


In [1]:
import numpy as np

    2. Crea un array de 1 dimension y 10 elementos.


In [2]:
arr1 = np.random.randint(100,1000, (10))
arr1

array([334, 130, 484, 471, 234, 387, 725, 326, 949, 212])

    3. Reemplaza todos los números impares por el valor "impar" y los pares por "par". Para hacer esto os tendréis que crear un array nuevo donde vayáis añadiendo los valores nuevos.


In [3]:
arr2 = np.empty_like(arr1, dtype = object ) #creamos un array con las mismas características que el anterior
arr2

array([None, None, None, None, None, None, None, None, None, None],
      dtype=object)

In [21]:
for i in range(0, arr1.shape[0]): ## iteramos por el primer array, si es par, agregamos par en el segundo array
    if arr1[i]%2 == 0:
        arr2[i] = "par"
    elif arr1[i]%2 != 0:
        arr2[i] = "impar"

In [5]:
arr2

array(['par', 'par', 'par', 'impar', 'par', 'impar', 'impar', 'par',
       'impar', 'par'], dtype=object)

    4. Cambiad la forma del array del ejercicio 3 a un array de 2 filas y 5 columnas.


In [6]:
arr3 = np.reshape(arr2, (2,5))
arr3

array([['par', 'par', 'par', 'impar', 'par'],
       ['impar', 'impar', 'par', 'impar', 'par']], dtype=object)

    5. Extrae los elementos comunes de los siguientes arrays
        array1 = np.array([1,2,3,2,3,4,3,4,5,6])
        array2 = np.array([7,2,10,2,7,4,9,4,9,8])


In [7]:
array1 = np.array([1,2,3,2,3,4,3,4,5,6])
array2 = np.array([7,2,10,2,7,4,9,4,9,8])

In [8]:
array3 = np.intersect1d(array1, array2)
array3

array([2, 4])

    6. Extraed los elementos que están en el array1 pero no en el array2.


In [9]:
array4 = np.setdiff1d(array1, array2)
array4

array([1, 3, 5, 6])

    7. Extraed las posiciones donde tengamos elementos que sean iguales.


In [25]:
array1 = np.array([1,2,3,2,3,4,3,4,5,6])
array2 = np.array([7,2,10,2,7,4,9,4,9,8])

In [26]:
posiciones = np.where(array1 == array2)

In [27]:
print(f"las posiciones del array2 donde se encuentran los elementos comunes del array1 son :", posiciones)

las posiciones del array2 donde se encuentran los elementos comunes del array1 son : (array([1, 3, 5, 7]),)


    8. Cread un array de 3 filas y 5 columnas, con números enteros del 0 al 50. Una vez creado, extrae los valores que sean menores que 10 y mayores que 40.


In [13]:
arr4 = np.random.randint(0,50, (3,5))
arr4

array([[43, 36,  6, 39, 27],
       [32, 44,  6,  8,  8],
       [34, 23, 10, 13, 16]])

In [14]:
valores = arr4[(arr4 < 10) | (arr4 > 40)]
valores

array([43,  6, 44,  6,  8,  8])

    9. Cread un array de 5x3 con números decimales aleatorios entre el 5 y el 10.


In [15]:
arr5 = np.random.uniform(5, 10, (5,3))
arr5

array([[6.05613545, 8.50008497, 7.63937075],
       [8.38793238, 7.50377089, 6.02597989],
       [9.14940692, 7.98829551, 8.57567463],
       [7.25916725, 6.70563783, 9.3446754 ],
       [5.3712799 , 7.97450369, 7.62799428]])

    10. Crea un array de tres dimensiones de 2x4x7 con números entre el 1 y el 20


In [16]:
arr6 = np.random.randint(1, 20, (2,4,7))
arr6

array([[[17, 10,  9, 11, 10, 14, 13],
        [19, 17, 10, 14, 13, 19, 11],
        [ 5,  5, 17, 17,  7, 17, 14],
        [ 2,  2,  8, 11, 14,  4,  9]],

       [[ 7,  5, 14,  4, 18, 11,  9],
        [16, 13, 17,  3,  1,  7, 12],
        [11,  1, 16, 16, 13,  3,  7],
        [ 8,  3, 10, 12,  2, 14, 17]]])

        10.1 Transponed el array para que tenga 4 matrices, 7 filas y 2 columnas


In [17]:
arr7 = np.reshape(arr6, (4,7,2)) ## lo hacemos con los métodos 
arr8 = np.transpose(arr6, (1,2,0))
arr7

array([[[17, 10],
        [ 9, 11],
        [10, 14],
        [13, 19],
        [17, 10],
        [14, 13],
        [19, 11]],

       [[ 5,  5],
        [17, 17],
        [ 7, 17],
        [14,  2],
        [ 2,  8],
        [11, 14],
        [ 4,  9]],

       [[ 7,  5],
        [14,  4],
        [18, 11],
        [ 9, 16],
        [13, 17],
        [ 3,  1],
        [ 7, 12]],

       [[11,  1],
        [16, 16],
        [13,  3],
        [ 7,  8],
        [ 3, 10],
        [12,  2],
        [14, 17]]])

In [18]:
arr8

array([[[17,  7],
        [10,  5],
        [ 9, 14],
        [11,  4],
        [10, 18],
        [14, 11],
        [13,  9]],

       [[19, 16],
        [17, 13],
        [10, 17],
        [14,  3],
        [13,  1],
        [19,  7],
        [11, 12]],

       [[ 5, 11],
        [ 5,  1],
        [17, 16],
        [17, 16],
        [ 7, 13],
        [17,  3],
        [14,  7]],

       [[ 2,  8],
        [ 2,  3],
        [ 8, 10],
        [11, 12],
        [14,  2],
        [ 4, 14],
        [ 9, 17]]])